require("alex_untitled.plugins")
require("alex_untitled.keymaps")
require("alex_untitled.lsp")
require("alex_untitled.autocomplete")
require("alex_untitled.formatting")
require("alex_untitled.navigation")
require("alex_untitled.core")
