set nocompatible
set t_Co=256
syntax enable

filetype on
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

if filereadable(expand("~/.vim/Vundlefile"))
  source ~/.vim/Vundlefile
endif

call vundle#end()

" Indentation
set autoindent
set listchars=tab:▸\ ,eol:¬
filetype plugin indent on

" Misc filetype hacks
if has("autocmd")
  augroup fthacks
    autocmd BufRead,BufNewFile */Vundlefile setfiletype ruby
  augroup END
end

" Color/theme stuff, including monkey-patched colors
colorscheme gruvbox
set background=dark
highlight clear SignColumn

" iTerm stuff
let &titlestring = expand("%:t")
if &term == "screen" || &term == "xterm-256color"
	set t_ts=]1;
	set t_fs=
endif
if &term == "screen" || &term == "xterm" || &term == "xterm-256color"
  set title
endif

if has("autocmd")
  augroup iterm
    autocmd BufEnter * let &titlestring = expand("%:t")
    autocmd BufEnter * set title
  augroup END
end

" Search stuff
let g:ag_working_path_mode="r"

" Airline setup
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ":t"
let g:airline_theme="gruvbox"

set completefunc=syntaxcomplete#Complete

" Prose environment
let g:vim_markdown_frontmatter=1
let g:pencil#wrapModeDefault = 'soft'

let g:jsx_ext_required = 0

if has("autocmd")
  augroup pencil
    autocmd!
    autocmd FileType markdown,mkd,md call pencil#init()
    autocmd FileType text call pencil#init({'wrap': 'hard'})
  augroup END
endif

" Miscellaneous plugin stuff
let g:NERDTreeWinSize=30
let g:NERDSpaceDelims=1
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=80
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
let g:ctrlp_extensions = ['undo']
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

" Settings
set autoread
set directory-=.
set encoding=utf-8
set incsearch
set number
set ruler
set showcmd
set smartcase
set wildignore=log/**,*/node_modules/**,target/**,tmp/**,vendor/**,public/**,*.rbc,*.pyc,elm-stuff/**
set hidden
set laststatus=2
set timeoutlen=1000 ttimeoutlen=0
set so=10
set noswapfile
set fdm=manual
set diffopt=filler,iwhite

set clipboard=unnamed
set mouse=a

set shiftwidth=2
set softtabstop=2
set tabstop=2
set backspace=2
set expandtab

" custom commands
command PPJson :%!python -m json.tool

" keyboard shortcuts
let mapleader = ','

nnoremap <Tab> :bn<CR>
nnoremap <S-Tab> :bp<CR>
nnoremap <leader>w :bd<CR>
nnoremap <leader>W :bd!<CR>
nnoremap <leader>a :nohlsearch<CR>

nnoremap <leader>C :s/^\(\d\+\.\s\{1}\)\(.\+\)$/\1\~\~\2\~\~/<CR>

nnoremap <leader>p :e ~/.vimrc<CR>
nnoremap <leader>P :e ~/.vim/Vundlefile<CR>
nnoremap <leader>S :source ~/.vimrc<CR>

nnoremap <leader>g :Goyo<CR>
nnoremap <leader>d :NERDTreeToggle<CR>
nnoremap <leader>D :NERDTree %<CR>
nnoremap <leader>f :NERDTreeFind<CR>
nnoremap <leader>t :CtrlP<CR>
nnoremap <leader>T :CtrlPClearCache<CR>:CtrlP<CR>
