set nocompatible
syntax enable

filetype on
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

if filereadable(expand("~/.vim/Vundlefile"))
  source ~/.vim/Vundlefile
endif

call vundle#end()

" Indentation
set autoindent
set listchars=tab:▸\ ,eol:¬
filetype plugin indent on

" Misc filetype hacks
if has("autocmd")
  augroup fthacks
    autocmd BufRead,BufNewFile */Vundlefile setfiletype ruby
  augroup END
end

" Color/theme stuff, including monkey-patched colors
let base16colorspace=256
colorscheme base16-railscasts
set background=dark
highlight clear SignColumn

" iTerm stuff
let &titlestring = expand("%:t")
if &term == "screen" || &term == "xterm-256color"
	set t_ts=]1;
	set t_fs=
endif
if &term == "screen" || &term == "xterm" || &term == "xterm-256color"
  set title
endif

if has("autocmd")
  augroup iterm
    autocmd BufEnter * let &titlestring = expand("%:t")
    autocmd BufEnter * set title
  augroup END
end

" Search stuff
let g:ag_working_path_mode="r"

" Project/filetype-specific stuff
if has("autocmd")
  augroup opal
    autocmd BufNewFile,BufRead ~/Sites/opal/* setlocal noexpandtab
    autocmd BufNewFile,BufRead ~/Sites/opal/* let b:vimrubocop_config='~/Sites/opal/.rubocop.yml'
  augroup END
endif

" Airline setup
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ":t"
let g:airline_theme="base16"

" Testing
let g:rspec_runner = "os_x_iterm"
let g:rspec_command = "!bundle exec rspec {spec}"
set completefunc=syntaxcomplete#Complete

" Prose environment
let g:vim_markdown_frontmatter=1
let g:pencil#wrapModeDefault = 'soft'

augroup pencil
  autocmd!
  autocmd FileType markdown,mkd,md call pencil#init()
  autocmd FileType text call pencil#init({'wrap': 'hard'})
augroup END

" Miscellaneous plugin stuff
let NERDTreeQuitOnOpen=1
let g:NERDTreeWinSize=50
" let g:ctrlp_max_files=0

" Settings
set autoread
set directory-=.
set encoding=utf-8
set incsearch
set number
set ruler
set showcmd
set smartcase
set wildignore=log/**,*/node_modules/**,target/**,tmp/**,vendor/**,public/**,*.rbc,*.pyc
set hidden
set laststatus=2
set timeoutlen=1000 ttimeoutlen=0
set so=5
set noswapfile

set clipboard=unnamed
set mouse=a

set shiftwidth=2
set softtabstop=2
set tabstop=2
set backspace=2
set expandtab

" keyboard shortcuts
let mapleader = ','

" language-specific stuff
nnoremap <leader>e :!mix test<CR>
nnoremap <leader>E :!mix credo<CR>

nnoremap <Tab> :bn<CR>
nnoremap <S-Tab> :bp<CR>
nnoremap <leader>w :bd<CR>
nnoremap <leader>W :bd!<CR>
nnoremap <leader>a :nohlsearch<CR>

nnoremap <leader>C :s/^\(\d\+\.\s\{1}\)\(.\+\)$/\1\~\~\2\~\~/<CR>

nnoremap <leader>p :e ~/.vimrc<CR>
nnoremap <leader>P :e ~/.vim/Vundlefile<CR>
nnoremap <leader>S :source ~/.vimrc<CR>

nnoremap <leader>g :Goyo<CR>
nnoremap <leader>d :NERDTreeToggle<CR>
nnoremap <leader>f :NERDTreeFind<CR>
nnoremap <leader>t :CtrlP<CR>
nnoremap <leader>T :CtrlPClearCache<CR>:CtrlP<CR>
