set nocompatible
syntax enable

" Vundler stuff
" To update, source ~/.Vundlefile and then :PluginInstall
filetype on
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

if filereadable(expand("~/.vim/Vundlefile"))
  source ~/.vim/Vundlefile
endif

call vundle#end()

" Indentation
set autoindent
set listchars=tab:▸\ ,eol:¬
filetype plugin indent on

" Color/theme stuff, including monkey-patched colors
colorscheme sourcerer
set background=dark
highlight clear SignColumn

hi NERDTreeDir ctermfg=137
hi NERDTreeUp ctermfg=137
hi NERDTreeCWD ctermfg=245

" Airline setup
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ":t"
let g:airline_theme="ubaryd"

" Miscellany
set autoread
set directory-=.
set encoding=utf-8
set incsearch
set number
set ruler
set showcmd
set smartcase
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc,*.pyc
set hidden
set laststatus=2
set mouse=a

set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

" Project-specific stuff
if has("autocmd")
  autocmd BufNewFile,BufRead ~/Sites/opal/* setlocal noexpandtab
endif

" keyboard shortcuts
let mapleader = ','

noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
nnoremap <Tab> :bn<CR>
nnoremap <S-Tab> :bp<CR>
nnoremap <C-w> :bd<CR>
nnoremap <C-W> :bd!<CR>

nnoremap <leader>p :e ~/.vimrc<CR>
nnoremap <leader>P :e ~/.Vundlefile<CR>
nnoremap <leader>S :source ~/.vimrc<CR>

nnoremap <leader>d :NERDTreeToggle<CR>
nnoremap <leader>f :NERDTreeFind<CR>
nnoremap <leader>t :CtrlP<CR>
nnoremap <leader>T :CtrlPClearCache<CR>:CtrlP<CR>
