# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="nanotech"
plugins=(git)
source $ZSH/oh-my-zsh.sh

if [ -d /Users/alex ]; then
  export PATH="/Users/alex/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin"
fi

export EDITOR="vim"

# yarn
export PATH="$PATH:`yarn global bin`"

# rbenv shims
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# pyenv shims
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# nvm
export NVM_DIR=~/.nvm

if which brew > /dev/null; then
  source $(brew --prefix nvm)/nvm.sh
fi

# rustup
export PATH="$HOME/.cargo/bin:$PATH"

# load alias files from ~/.aliases
for f in ~/.aliases/*.aliases
do
  source $f
done

# apply local alias files to override files from SCM
for f in ~/.aliases/*.aliases.local
do
  source $f
done

if [ -f ~/.home_env.sh ]; then
  source ~/.home_env.sh
fi

if [ -f ~/.work_env.sh ]; then
  source ~/.work_env.sh
fi
