# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="nanotech"
plugins=(git)
source $ZSH/oh-my-zsh.sh

if [ -d /Users/alex ]; then
  export PATH="/Users/alex/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin"
fi

export EDITOR="vim"

# yarn
export PATH="$PATH:`yarn global bin`"

# rbenv shims
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# asdf version-manager
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# aliases
alias cdn='cd ~/source/nutshell'
alias cdf='cd ~/flux'
alias cdth='cd ~/p/gruvbox-dark-ui'

# work stuff
if [[ -d "$HOME/nub" ]]; then
	eval "$($HOME/nub/bin/nub init -)"
fi
