# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="nanotech"
plugins=(git)
source $ZSH/oh-my-zsh.sh

export PATH="/Users/alex/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin"
export EDITOR="vim"

alias ll="ls -lahL"

# rbenv shims
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# nvm
source $(brew --prefix nvm)/nvm.sh

# load alias files from ~/.aliases
for f in ~/.aliases/aliases.*
do
  source $f
done
